version: '3.9'

services:
  api:
    build: .
    container_name: my-api
    ports:
      - "8080:8080"
    environment:
      - MongoDb__ConnectionString=mongodb+srv://eupedrohfo_db_user:Asdw0258qwe%40@teste.f6oi1p6.mongodb.net/
      - MongoDb__DatabaseName=Teste